DATA_ROOT: '/home/djordje/Documents/Projects/instance_association/GNN-CCA'
DATASET_TRAIN:
    NAME: [EPFL-Terrace, EPFL-Laboratory]
    IMAUG: True
    RESIZE: [128, 64]
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    ZERO_PADDING: False

MAX_DIST: # dist/CONV_TO_M to covert to meters
    PETS2009_S2_L1_5_8: 26.56
    EPFL-Laboratory: 44.23
    EPFL-Terrace: 50.83
    CAMPUS_Garden1: 85.23
    AIC20-S01: 0.00001
    AIC20-S02: 0.00001
    EPFL-Basketball: 153.54

DATASET_VAL:
    NAME: EPFL-Basketball
    RESIZE: [128, 64]
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    ZERO_PADDING: False

DATALOADER:
    NUM_WORKERS: 4
    PIN_MEMORY: True

CNN_MODEL:
    model_weights_path: /home/djordje/Documents/Projects/instance_association/GNN-CCA/trained_models/reid/resnet50_market_cuhk_duke.tar-232
    L2norm: True